# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1383, 887)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabEdit = QtGui.QWidget()
        self.tabEdit.setObjectName(_fromUtf8("tabEdit"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tabEdit)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.statusPanel = QtGui.QHBoxLayout()
        self.statusPanel.setObjectName(_fromUtf8("statusPanel"))
        self.playButton = QtGui.QPushButton(self.tabEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.statusPanel.addWidget(self.playButton)
        self.seekSlider = QtGui.QSlider(self.tabEdit)
        self.seekSlider.setMaximum(1000)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName(_fromUtf8("seekSlider"))
        self.statusPanel.addWidget(self.seekSlider)
        self.status = QtGui.QLabel(self.tabEdit)
        self.status.setText(_fromUtf8(""))
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName(_fromUtf8("status"))
        self.statusPanel.addWidget(self.status)
        self.gridLayout_3.addLayout(self.statusPanel, 1, 0, 1, 1)
        self.splitterVertical = QtGui.QSplitter(self.tabEdit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterVertical.sizePolicy().hasHeightForWidth())
        self.splitterVertical.setSizePolicy(sizePolicy)
        self.splitterVertical.setOrientation(QtCore.Qt.Vertical)
        self.splitterVertical.setChildrenCollapsible(True)
        self.splitterVertical.setObjectName(_fromUtf8("splitterVertical"))
        self.upperPanel = QtGui.QWidget(self.splitterVertical)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperPanel.sizePolicy().hasHeightForWidth())
        self.upperPanel.setSizePolicy(sizePolicy)
        self.upperPanel.setObjectName(_fromUtf8("upperPanel"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.upperPanel)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.toolbar = QtGui.QWidget(self.upperPanel)
        self.toolbar.setObjectName(_fromUtf8("toolbar"))
        self.horizontalLayout_2.addWidget(self.toolbar)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.splitterEditTop = QtGui.QSplitter(self.upperPanel)
        self.splitterEditTop.setOrientation(QtCore.Qt.Horizontal)
        self.splitterEditTop.setObjectName(_fromUtf8("splitterEditTop"))
        self.graphicsView = AnnotateView(self.splitterEditTop)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(320, 180))
        self.graphicsView.setBaseSize(QtCore.QSize(0, 0))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphicsView.setResizeAnchor(QtGui.QGraphicsView.NoAnchor)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitterEditTop)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayoutRight = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutRight.setSpacing(6)
        self.verticalLayoutRight.setObjectName(_fromUtf8("verticalLayoutRight"))
        self.propertyWidget = PropertyWidget(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyWidget.sizePolicy().hasHeightForWidth())
        self.propertyWidget.setSizePolicy(sizePolicy)
        self.propertyWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.propertyWidget.setAlternatingRowColors(True)
        self.propertyWidget.setItemsExpandable(True)
        self.propertyWidget.setAllColumnsShowFocus(False)
        self.propertyWidget.setColumnCount(2)
        self.propertyWidget.setObjectName(_fromUtf8("propertyWidget"))
        self.propertyWidget.header().setCascadingSectionResizes(False)
        self.propertyWidget.header().setDefaultSectionSize(80)
        self.propertyWidget.header().setStretchLastSection(True)
        self.verticalLayoutRight.addWidget(self.propertyWidget)
        self.buttonVariables = QtGui.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonVariables.sizePolicy().hasHeightForWidth())
        self.buttonVariables.setSizePolicy(sizePolicy)
        self.buttonVariables.setObjectName(_fromUtf8("buttonVariables"))
        self.verticalLayoutRight.addWidget(self.buttonVariables)
        self.horizontalLayout_2.addWidget(self.splitterEditTop)
        self.lowerPanel = QtGui.QWidget(self.splitterVertical)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerPanel.sizePolicy().hasHeightForWidth())
        self.lowerPanel.setSizePolicy(sizePolicy)
        self.lowerPanel.setObjectName(_fromUtf8("lowerPanel"))
        self.gridLayout_4 = QtGui.QGridLayout(self.lowerPanel)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter = QtGui.QSplitter(self.lowerPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.videoPlayer = QtGui.QFrame(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.videoPlayer.setPalette(palette)
        self.videoPlayer.setAutoFillBackground(True)
        self.videoPlayer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.videoPlayer.setFrameShadow(QtGui.QFrame.Raised)
        self.videoPlayer.setObjectName(_fromUtf8("videoPlayer"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.items = PathTableWidget(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.items.sizePolicy().hasHeightForWidth())
        self.items.setSizePolicy(sizePolicy)
        self.items.setStyleSheet(_fromUtf8("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(190, 204, 255);\n"
""))
        self.items.setAlternatingRowColors(True)
        self.items.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.items.setColumnCount(1)
        self.items.setObjectName(_fromUtf8("items"))
        self.items.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.items.setHorizontalHeaderItem(0, item)
        self.items.horizontalHeader().setVisible(False)
        self.items.horizontalHeader().setDefaultSectionSize(100)
        self.items.horizontalHeader().setMinimumSectionSize(100)
        self.items.horizontalHeader().setSortIndicatorShown(True)
        self.items.horizontalHeader().setStretchLastSection(True)
        self.items.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.items)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.filterTracks = QtGui.QPushButton(self.layoutWidget)
        self.filterTracks.setObjectName(_fromUtf8("filterTracks"))
        self.horizontalLayout_3.addWidget(self.filterTracks)
        self.checkAll = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkAll.sizePolicy().hasHeightForWidth())
        self.checkAll.setSizePolicy(sizePolicy)
        self.checkAll.setObjectName(_fromUtf8("checkAll"))
        self.horizontalLayout_3.addWidget(self.checkAll)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitterVertical, 0, 0, 1, 1)
        self.progressBarEdit = QtGui.QProgressBar(self.tabEdit)
        self.progressBarEdit.setProperty("value", 24)
        self.progressBarEdit.setTextVisible(True)
        self.progressBarEdit.setObjectName(_fromUtf8("progressBarEdit"))
        self.gridLayout_3.addWidget(self.progressBarEdit, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabEdit, _fromUtf8(""))
        self.tabSearch = QtGui.QWidget()
        self.tabSearch.setObjectName(_fromUtf8("tabSearch"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabSearch)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitterSearch = QtGui.QSplitter(self.tabSearch)
        self.splitterSearch.setOrientation(QtCore.Qt.Horizontal)
        self.splitterSearch.setObjectName(_fromUtf8("splitterSearch"))
        self.searchWidget = QtGui.QWidget(self.splitterSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchWidget.sizePolicy().hasHeightForWidth())
        self.searchWidget.setSizePolicy(sizePolicy)
        self.searchWidget.setObjectName(_fromUtf8("searchWidget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.searchWidget)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.splitter_2 = QtGui.QSplitter(self.searchWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.widgetFilter = QtGui.QWidget(self.splitter_2)
        self.widgetFilter.setObjectName(_fromUtf8("widgetFilter"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widgetFilter)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.topGridLayout = QtGui.QGridLayout()
        self.topGridLayout.setObjectName(_fromUtf8("topGridLayout"))
        self.listScrollArea = QtGui.QScrollArea(self.widgetFilter)
        self.listScrollArea.setWidgetResizable(True)
        self.listScrollArea.setObjectName(_fromUtf8("listScrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 630, 111))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_9 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.listArea = QtGui.QToolBox(self.scrollAreaWidgetContents)
        self.listArea.setObjectName(_fromUtf8("listArea"))
        self.listAreaPage1 = QtGui.QWidget()
        self.listAreaPage1.setGeometry(QtCore.QRect(0, 0, 612, 69))
        self.listAreaPage1.setBaseSize(QtCore.QSize(0, 0))
        self.listAreaPage1.setObjectName(_fromUtf8("listAreaPage1"))
        self.listArea.addItem(self.listAreaPage1, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.listArea, 0, 0, 1, 1)
        self.listScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.topGridLayout.addWidget(self.listScrollArea, 1, 0, 1, 1)
        self.checkboxScrollArea = QtGui.QScrollArea(self.widgetFilter)
        self.checkboxScrollArea.setWidgetResizable(True)
        self.checkboxScrollArea.setObjectName(_fromUtf8("checkboxScrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 646, 107))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.checkboxArea = QtGui.QVBoxLayout()
        self.checkboxArea.setObjectName(_fromUtf8("checkboxArea"))
        self.gridLayout_10.addLayout(self.checkboxArea, 0, 0, 1, 1)
        self.checkboxScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.topGridLayout.addWidget(self.checkboxScrollArea, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.topGridLayout, 0, 0, 1, 1)
        self.widgetAOI = QtGui.QWidget(self.splitter_2)
        self.widgetAOI.setObjectName(_fromUtf8("widgetAOI"))
        self.gridLayout_13 = QtGui.QGridLayout(self.widgetAOI)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.useAOIs = QtGui.QCheckBox(self.widgetAOI)
        self.useAOIs.setObjectName(_fromUtf8("useAOIs"))
        self.horizontalLayout_4.addWidget(self.useAOIs)
        self.updateStats = QtGui.QPushButton(self.widgetAOI)
        self.updateStats.setObjectName(_fromUtf8("updateStats"))
        self.horizontalLayout_4.addWidget(self.updateStats)
        self.exportStats = QtGui.QPushButton(self.widgetAOI)
        self.exportStats.setObjectName(_fromUtf8("exportStats"))
        self.horizontalLayout_4.addWidget(self.exportStats)
        self.exportAOIData = QtGui.QPushButton(self.widgetAOI)
        self.exportAOIData.setObjectName(_fromUtf8("exportAOIData"))
        self.horizontalLayout_4.addWidget(self.exportAOIData)
        self.showHistogram = QtGui.QPushButton(self.widgetAOI)
        self.showHistogram.setObjectName(_fromUtf8("showHistogram"))
        self.horizontalLayout_4.addWidget(self.showHistogram)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.aois = AOITableWidget(self.widgetAOI)
        self.aois.setObjectName(_fromUtf8("aois"))
        self.aois.setColumnCount(4)
        self.aois.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(3, item)
        self.aois.horizontalHeader().setDefaultSectionSize(80)
        self.aois.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_13.addWidget(self.aois, 1, 0, 1, 1)
        self.widgetTime = QtGui.QWidget(self.splitter_2)
        self.widgetTime.setObjectName(_fromUtf8("widgetTime"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widgetTime)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.searchButtonLayout = QtGui.QHBoxLayout()
        self.searchButtonLayout.setObjectName(_fromUtf8("searchButtonLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem)
        self.searchButton = QtGui.QPushButton(self.widgetTime)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.searchButtonLayout.addWidget(self.searchButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem1)
        self.searchCancel = QtGui.QPushButton(self.widgetTime)
        self.searchCancel.setObjectName(_fromUtf8("searchCancel"))
        self.searchButtonLayout.addWidget(self.searchCancel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.searchButtonLayout, 2, 0, 1, 1)
        self.groupTimeEvents = QtGui.QGroupBox(self.widgetTime)
        self.groupTimeEvents.setObjectName(_fromUtf8("groupTimeEvents"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupTimeEvents)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.startTimeFilter = QtGui.QTimeEdit(self.groupTimeEvents)
        self.startTimeFilter.setObjectName(_fromUtf8("startTimeFilter"))
        self.gridLayout_8.addWidget(self.startTimeFilter, 0, 1, 1, 1)
        self.timeCheckBox = QtGui.QCheckBox(self.groupTimeEvents)
        self.timeCheckBox.setObjectName(_fromUtf8("timeCheckBox"))
        self.gridLayout_8.addWidget(self.timeCheckBox, 0, 0, 1, 1)
        self.stopTimeFilter = QtGui.QTimeEdit(self.groupTimeEvents)
        self.stopTimeFilter.setObjectName(_fromUtf8("stopTimeFilter"))
        self.gridLayout_8.addWidget(self.stopTimeFilter, 0, 2, 1, 1)
        self.maxClusterDistance = QtGui.QSpinBox(self.groupTimeEvents)
        self.maxClusterDistance.setProperty("value", 3)
        self.maxClusterDistance.setObjectName(_fromUtf8("maxClusterDistance"))
        self.gridLayout_8.addWidget(self.maxClusterDistance, 1, 2, 1, 1)
        self.maxClusterTime = QtGui.QDoubleSpinBox(self.groupTimeEvents)
        self.maxClusterTime.setProperty("value", 0.3)
        self.maxClusterTime.setObjectName(_fromUtf8("maxClusterTime"))
        self.gridLayout_8.addWidget(self.maxClusterTime, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupTimeEvents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupTimeEvents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 2, 1, 1, 1)
        self.removeClusters = QtGui.QCheckBox(self.groupTimeEvents)
        self.removeClusters.setObjectName(_fromUtf8("removeClusters"))
        self.gridLayout_8.addWidget(self.removeClusters, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupTimeEvents, 1, 0, 1, 1)
        self.results = QtGui.QTableWidget(self.splitter_2)
        self.results.setMouseTracking(True)
        self.results.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.results.setAlternatingRowColors(True)
        self.results.setRowCount(0)
        self.results.setColumnCount(2)
        self.results.setObjectName(_fromUtf8("results"))
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.results.setHorizontalHeaderItem(1, item)
        self.results.horizontalHeader().setStretchLastSection(True)
        self.results.verticalHeader().setStretchLastSection(False)
        self.groupVisualize = QtGui.QGroupBox(self.splitter_2)
        self.groupVisualize.setObjectName(_fromUtf8("groupVisualize"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupVisualize)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.groupVisualize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.visRadius = QtGui.QSpinBox(self.groupVisualize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visRadius.sizePolicy().hasHeightForWidth())
        self.visRadius.setSizePolicy(sizePolicy)
        self.visRadius.setMinimum(1)
        self.visRadius.setMaximum(100)
        self.visRadius.setProperty("value", 15)
        self.visRadius.setObjectName(_fromUtf8("visRadius"))
        self.horizontalLayout_5.addWidget(self.visRadius)
        self.label_2 = QtGui.QLabel(self.groupVisualize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.visAlpha = QtGui.QSpinBox(self.groupVisualize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visAlpha.sizePolicy().hasHeightForWidth())
        self.visAlpha.setSizePolicy(sizePolicy)
        self.visAlpha.setMinimum(1)
        self.visAlpha.setMaximum(100)
        self.visAlpha.setProperty("value", 50)
        self.visAlpha.setObjectName(_fromUtf8("visAlpha"))
        self.horizontalLayout_5.addWidget(self.visAlpha)
        self.label_5 = QtGui.QLabel(self.groupVisualize)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.colorScale = QtGui.QDoubleSpinBox(self.groupVisualize)
        self.colorScale.setDecimals(1)
        self.colorScale.setMaximum(10.0)
        self.colorScale.setSingleStep(0.1)
        self.colorScale.setProperty("value", 1.0)
        self.colorScale.setObjectName(_fromUtf8("colorScale"))
        self.horizontalLayout_5.addWidget(self.colorScale)
        self.visUseTime = QtGui.QCheckBox(self.groupVisualize)
        self.visUseTime.setObjectName(_fromUtf8("visUseTime"))
        self.horizontalLayout_5.addWidget(self.visUseTime)
        self.visButton = QtGui.QPushButton(self.groupVisualize)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visButton.sizePolicy().hasHeightForWidth())
        self.visButton.setSizePolicy(sizePolicy)
        self.visButton.setObjectName(_fromUtf8("visButton"))
        self.horizontalLayout_5.addWidget(self.visButton)
        self.exportImage = QtGui.QPushButton(self.groupVisualize)
        self.exportImage.setObjectName(_fromUtf8("exportImage"))
        self.horizontalLayout_5.addWidget(self.exportImage)
        self.exportData = QtGui.QPushButton(self.groupVisualize)
        self.exportData.setObjectName(_fromUtf8("exportData"))
        self.horizontalLayout_5.addWidget(self.exportData)
        self.exportVideo = QtGui.QPushButton(self.groupVisualize)
        self.exportVideo.setObjectName(_fromUtf8("exportVideo"))
        self.horizontalLayout_5.addWidget(self.exportVideo)
        self.exportCancel = QtGui.QPushButton(self.groupVisualize)
        self.exportCancel.setObjectName(_fromUtf8("exportCancel"))
        self.horizontalLayout_5.addWidget(self.exportCancel)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.searchWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_7.addWidget(self.progressBar, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.splitterSearch)
        self.tabWidget.addTab(self.tabSearch, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.listArea.layout().setSpacing(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.playButton.setShortcut(_translate("MainWindow", "Space", None))
        self.propertyWidget.headerItem().setText(0, _translate("MainWindow", "Property", None))
        self.propertyWidget.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.buttonVariables.setText(_translate("MainWindow", "Variables", None))
        self.items.setSortingEnabled(True)
        item = self.items.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Path", None))
        self.filterTracks.setText(_translate("MainWindow", "Filter", None))
        self.checkAll.setText(_translate("MainWindow", "Check/Uncheck All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEdit), _translate("MainWindow", "Edit", None))
        self.useAOIs.setText(_translate("MainWindow", "Use AOIs", None))
        self.updateStats.setText(_translate("MainWindow", "Update Stats", None))
        self.exportStats.setText(_translate("MainWindow", "Export Stats", None))
        self.exportAOIData.setText(_translate("MainWindow", "Export Individual Data", None))
        self.showHistogram.setText(_translate("MainWindow", "Show Data Histogram", None))
        item = self.aois.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AOI", None))
        item = self.aois.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Average Duration (no zeros)", None))
        item = self.aois.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Percentage Fixated", None))
        item = self.aois.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Number of Subjects", None))
        self.searchButton.setText(_translate("MainWindow", "Search", None))
        self.searchCancel.setText(_translate("MainWindow", "Cancel", None))
        self.groupTimeEvents.setTitle(_translate("MainWindow", "Events", None))
        self.startTimeFilter.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.timeCheckBox.setText(_translate("MainWindow", "Time", None))
        self.stopTimeFilter.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.maxClusterDistance.setSuffix(_translate("MainWindow", "%", None))
        self.maxClusterTime.setSuffix(_translate("MainWindow", " sec", None))
        self.label_3.setText(_translate("MainWindow", "Max Cluster Distance", None))
        self.label_4.setText(_translate("MainWindow", "Max Cluster Time", None))
        self.removeClusters.setText(_translate("MainWindow", "Remove Clustered Points", None))
        self.results.setSortingEnabled(True)
        item = self.results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time", None))
        self.groupVisualize.setTitle(_translate("MainWindow", "Visualization", None))
        self.label.setText(_translate("MainWindow", "Radius", None))
        self.visRadius.setSuffix(_translate("MainWindow", " %", None))
        self.label_2.setText(_translate("MainWindow", "Alpha", None))
        self.visAlpha.setSuffix(_translate("MainWindow", " %", None))
        self.label_5.setText(_translate("MainWindow", "Color Scale", None))
        self.visUseTime.setText(_translate("MainWindow", "Time", None))
        self.visButton.setText(_translate("MainWindow", "Visualize", None))
        self.exportImage.setText(_translate("MainWindow", "Export Image", None))
        self.exportData.setText(_translate("MainWindow", "Export Data", None))
        self.exportVideo.setText(_translate("MainWindow", "Export Video", None))
        self.exportCancel.setText(_translate("MainWindow", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("MainWindow", "Search", None))

from annotateview import AnnotateView
from aoitablewidget import AOITableWidget
from pathtablewidget import PathTableWidget
from propertywidget import PropertyWidget
