# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(("MainWindow"))
        MainWindow.resize(1383, 887)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle((""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(("icons/icon.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName(("centralWidget"))
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setObjectName(("gridLayout_2"))
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(("tabWidget"))
        self.tabEdit = QtWidgets.QWidget()
        self.tabEdit.setObjectName(("tabEdit"))
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabEdit)
        self.gridLayout_3.setObjectName(("gridLayout_3"))
        self.statusPanel = QtWidgets.QHBoxLayout()
        self.statusPanel.setObjectName(("statusPanel"))
        self.playButton = QtWidgets.QPushButton(self.tabEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName(("playButton"))
        self.statusPanel.addWidget(self.playButton)
        self.seekSlider = QtWidgets.QSlider(self.tabEdit)
        self.seekSlider.setMaximum(1000)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName(("seekSlider"))
        self.statusPanel.addWidget(self.seekSlider)
        self.status = QtWidgets.QLabel(self.tabEdit)
        self.status.setText((""))
        self.status.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.status.setObjectName(("status"))
        self.statusPanel.addWidget(self.status)
        self.gridLayout_3.addLayout(self.statusPanel, 1, 0, 1, 1)
        self.splitterVertical = QtWidgets.QSplitter(self.tabEdit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterVertical.sizePolicy().hasHeightForWidth())
        self.splitterVertical.setSizePolicy(sizePolicy)
        self.splitterVertical.setOrientation(QtCore.Qt.Vertical)
        self.splitterVertical.setChildrenCollapsible(True)
        self.splitterVertical.setObjectName(("splitterVertical"))
        self.upperPanel = QtWidgets.QWidget(self.splitterVertical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upperPanel.sizePolicy().hasHeightForWidth())
        self.upperPanel.setSizePolicy(sizePolicy)
        self.upperPanel.setObjectName(("upperPanel"))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.upperPanel)
        self.horizontalLayout_2.setObjectName(("horizontalLayout_2"))
        self.toolbar = QtWidgets.QWidget(self.upperPanel)
        self.toolbar.setObjectName(("toolbar"))
        self.horizontalLayout_2.addWidget(self.toolbar)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName(("gridLayout"))
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.splitterEditTop = QtWidgets.QSplitter(self.upperPanel)
        self.splitterEditTop.setOrientation(QtCore.Qt.Horizontal)
        self.splitterEditTop.setObjectName(("splitterEditTop"))
        self.graphicsView = AnnotateView(self.splitterEditTop)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(320, 180))
        self.graphicsView.setBaseSize(QtCore.QSize(0, 0))
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView.setBackgroundBrush(brush)
        self.graphicsView.setSceneRect(QtCore.QRectF(0.0, 0.0, 0.0, 0.0))
        self.graphicsView.setResizeAnchor(QtWidgets.QGraphicsView.NoAnchor)
        self.graphicsView.setObjectName(("graphicsView"))
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitterEditTop)
        self.verticalLayoutWidget.setObjectName(("verticalLayoutWidget"))
        self.verticalLayoutRight = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayoutRight.setSpacing(6)
        self.verticalLayoutRight.setObjectName(("verticalLayoutRight"))
        self.propertyWidget = PropertyWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propertyWidget.sizePolicy().hasHeightForWidth())
        self.propertyWidget.setSizePolicy(sizePolicy)
        self.propertyWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.propertyWidget.setAlternatingRowColors(True)
        self.propertyWidget.setItemsExpandable(True)
        self.propertyWidget.setAllColumnsShowFocus(False)
        self.propertyWidget.setColumnCount(2)
        self.propertyWidget.setObjectName(("propertyWidget"))
        self.propertyWidget.header().setCascadingSectionResizes(False)
        self.propertyWidget.header().setDefaultSectionSize(80)
        self.propertyWidget.header().setStretchLastSection(True)
        self.verticalLayoutRight.addWidget(self.propertyWidget)
        self.buttonVariables = QtWidgets.QToolButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonVariables.sizePolicy().hasHeightForWidth())
        self.buttonVariables.setSizePolicy(sizePolicy)
        self.buttonVariables.setObjectName(("buttonVariables"))
        self.verticalLayoutRight.addWidget(self.buttonVariables)
        self.horizontalLayout_2.addWidget(self.splitterEditTop)
        self.lowerPanel = QtWidgets.QWidget(self.splitterVertical)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lowerPanel.sizePolicy().hasHeightForWidth())
        self.lowerPanel.setSizePolicy(sizePolicy)
        self.lowerPanel.setObjectName(("lowerPanel"))
        self.gridLayout_4 = QtWidgets.QGridLayout(self.lowerPanel)
        self.gridLayout_4.setObjectName(("gridLayout_4"))
        self.splitter = QtWidgets.QSplitter(self.lowerPanel)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(("splitter"))
        self.videoPlayer = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(80)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoPlayer.sizePolicy().hasHeightForWidth())
        self.videoPlayer.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.videoPlayer.setPalette(palette)
        self.videoPlayer.setAutoFillBackground(True)
        self.videoPlayer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.videoPlayer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.videoPlayer.setObjectName(("videoPlayer"))
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName(("layoutWidget"))
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(("verticalLayout"))
        self.items = PathTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.items.sizePolicy().hasHeightForWidth())
        self.items.setSizePolicy(sizePolicy)
        self.items.setStyleSheet(("selection-color: rgb(0, 0, 0);\n"
"selection-background-color: rgb(190, 204, 255);\n"
""))
        self.items.setAlternatingRowColors(True)
        self.items.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.items.setColumnCount(1)
        self.items.setObjectName(("items"))
        self.items.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.items.setHorizontalHeaderItem(0, item)
        self.items.horizontalHeader().setVisible(False)
        self.items.horizontalHeader().setDefaultSectionSize(100)
        self.items.horizontalHeader().setMinimumSectionSize(100)
        self.items.horizontalHeader().setSortIndicatorShown(True)
        self.items.horizontalHeader().setStretchLastSection(True)
        self.items.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.items)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(("horizontalLayout_3"))
        self.filterTracks = QtWidgets.QPushButton(self.layoutWidget)
        self.filterTracks.setObjectName(("filterTracks"))
        self.horizontalLayout_3.addWidget(self.filterTracks)
        self.checkAll = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkAll.sizePolicy().hasHeightForWidth())
        self.checkAll.setSizePolicy(sizePolicy)
        self.checkAll.setObjectName(("checkAll"))
        self.horizontalLayout_3.addWidget(self.checkAll)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_4.addWidget(self.splitter, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.splitterVertical, 0, 0, 1, 1)
        self.progressBarEdit = QtWidgets.QProgressBar(self.tabEdit)
        self.progressBarEdit.setProperty("value", 24)
        self.progressBarEdit.setTextVisible(True)
        self.progressBarEdit.setObjectName(("progressBarEdit"))
        self.gridLayout_3.addWidget(self.progressBarEdit, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabEdit, (""))
        self.tabSearch = QtWidgets.QWidget()
        self.tabSearch.setObjectName(("tabSearch"))
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabSearch)
        self.horizontalLayout.setObjectName(("horizontalLayout"))
        self.splitterSearch = QtWidgets.QSplitter(self.tabSearch)
        self.splitterSearch.setOrientation(QtCore.Qt.Horizontal)
        self.splitterSearch.setObjectName(("splitterSearch"))
        self.searchWidget = QtWidgets.QWidget(self.splitterSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchWidget.sizePolicy().hasHeightForWidth())
        self.searchWidget.setSizePolicy(sizePolicy)
        self.searchWidget.setObjectName(("searchWidget"))
        self.gridLayout_7 = QtWidgets.QGridLayout(self.searchWidget)
        self.gridLayout_7.setObjectName(("gridLayout_7"))
        self.splitter_2 = QtWidgets.QSplitter(self.searchWidget)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName(("splitter_2"))
        self.widgetFilter = QtWidgets.QWidget(self.splitter_2)
        self.widgetFilter.setObjectName(("widgetFilter"))
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widgetFilter)
        self.gridLayout_5.setObjectName(("gridLayout_5"))
        self.topGridLayout = QtWidgets.QGridLayout()
        self.topGridLayout.setObjectName(("topGridLayout"))
        self.listScrollArea = QtWidgets.QScrollArea(self.widgetFilter)
        self.listScrollArea.setWidgetResizable(True)
        self.listScrollArea.setObjectName(("listScrollArea"))
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 630, 111))
        self.scrollAreaWidgetContents.setObjectName(("scrollAreaWidgetContents"))
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_9.setObjectName(("gridLayout_9"))
        self.listArea = QtWidgets.QToolBox(self.scrollAreaWidgetContents)
        self.listArea.setObjectName(("listArea"))
        self.listAreaPage1 = QtWidgets.QWidget()
        self.listAreaPage1.setGeometry(QtCore.QRect(0, 0, 612, 69))
        self.listAreaPage1.setBaseSize(QtCore.QSize(0, 0))
        self.listAreaPage1.setObjectName(("listAreaPage1"))
        self.listArea.addItem(self.listAreaPage1, (""))
        self.gridLayout_9.addWidget(self.listArea, 0, 0, 1, 1)
        self.listScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.topGridLayout.addWidget(self.listScrollArea, 1, 0, 1, 1)
        self.checkboxScrollArea = QtWidgets.QScrollArea(self.widgetFilter)
        self.checkboxScrollArea.setWidgetResizable(True)
        self.checkboxScrollArea.setObjectName(("checkboxScrollArea"))
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 646, 107))
        self.scrollAreaWidgetContents_2.setObjectName(("scrollAreaWidgetContents_2"))
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName(("gridLayout_10"))
        self.checkboxArea = QtWidgets.QVBoxLayout()
        self.checkboxArea.setObjectName(("checkboxArea"))
        self.gridLayout_10.addLayout(self.checkboxArea, 0, 0, 1, 1)
        self.checkboxScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.topGridLayout.addWidget(self.checkboxScrollArea, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.topGridLayout, 0, 0, 1, 1)
        self.widgetAOI = QtWidgets.QWidget(self.splitter_2)
        self.widgetAOI.setObjectName(("widgetAOI"))
        self.gridLayout_13 = QtWidgets.QGridLayout(self.widgetAOI)
        self.gridLayout_13.setObjectName(("gridLayout_13"))
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(("horizontalLayout_4"))
        self.useAOIs = QtWidgets.QCheckBox(self.widgetAOI)
        self.useAOIs.setObjectName(("useAOIs"))
        self.horizontalLayout_4.addWidget(self.useAOIs)
        self.updateStats = QtWidgets.QPushButton(self.widgetAOI)
        self.updateStats.setObjectName(("updateStats"))
        self.horizontalLayout_4.addWidget(self.updateStats)
        self.exportStats = QtWidgets.QPushButton(self.widgetAOI)
        self.exportStats.setObjectName(("exportStats"))
        self.horizontalLayout_4.addWidget(self.exportStats)
        self.exportAOIData = QtWidgets.QPushButton(self.widgetAOI)
        self.exportAOIData.setObjectName(("exportAOIData"))
        self.horizontalLayout_4.addWidget(self.exportAOIData)
        self.showHistogram = QtWidgets.QPushButton(self.widgetAOI)
        self.showHistogram.setObjectName(("showHistogram"))
        self.horizontalLayout_4.addWidget(self.showHistogram)
        self.gridLayout_13.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.aois = AOITableWidget(self.widgetAOI)
        self.aois.setObjectName(("aois"))
        self.aois.setColumnCount(4)
        self.aois.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.aois.setHorizontalHeaderItem(3, item)
        self.aois.horizontalHeader().setDefaultSectionSize(80)
        self.aois.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_13.addWidget(self.aois, 1, 0, 1, 1)
        self.widgetTime = QtWidgets.QWidget(self.splitter_2)
        self.widgetTime.setObjectName(("widgetTime"))
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widgetTime)
        self.gridLayout_6.setObjectName(("gridLayout_6"))
        self.searchButtonLayout = QtWidgets.QHBoxLayout()
        self.searchButtonLayout.setObjectName(("searchButtonLayout"))
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem)
        self.searchButton = QtWidgets.QPushButton(self.widgetTime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setObjectName(("searchButton"))
        self.searchButtonLayout.addWidget(self.searchButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem1)
        self.searchCancel = QtWidgets.QPushButton(self.widgetTime)
        self.searchCancel.setObjectName(("searchCancel"))
        self.searchButtonLayout.addWidget(self.searchCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.searchButtonLayout.addItem(spacerItem2)
        self.gridLayout_6.addLayout(self.searchButtonLayout, 2, 0, 1, 1)
        self.groupTimeEvents = QtWidgets.QGroupBox(self.widgetTime)
        self.groupTimeEvents.setObjectName(("groupTimeEvents"))
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupTimeEvents)
        self.gridLayout_8.setObjectName(("gridLayout_8"))
        self.startTimeFilter = QtWidgets.QTimeEdit(self.groupTimeEvents)
        self.startTimeFilter.setObjectName(("startTimeFilter"))
        self.gridLayout_8.addWidget(self.startTimeFilter, 0, 1, 1, 1)
        self.timeCheckBox = QtWidgets.QCheckBox(self.groupTimeEvents)
        self.timeCheckBox.setObjectName(("timeCheckBox"))
        self.gridLayout_8.addWidget(self.timeCheckBox, 0, 0, 1, 1)
        self.stopTimeFilter = QtWidgets.QTimeEdit(self.groupTimeEvents)
        self.stopTimeFilter.setObjectName(("stopTimeFilter"))
        self.gridLayout_8.addWidget(self.stopTimeFilter, 0, 2, 1, 1)
        self.maxClusterDistance = QtWidgets.QSpinBox(self.groupTimeEvents)
        self.maxClusterDistance.setProperty("value", 3)
        self.maxClusterDistance.setObjectName(("maxClusterDistance"))
        self.gridLayout_8.addWidget(self.maxClusterDistance, 1, 2, 1, 1)
        self.maxClusterTime = QtWidgets.QDoubleSpinBox(self.groupTimeEvents)
        self.maxClusterTime.setProperty("value", 0.3)
        self.maxClusterTime.setObjectName(("maxClusterTime"))
        self.gridLayout_8.addWidget(self.maxClusterTime, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupTimeEvents)
        self.label_3.setObjectName(("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupTimeEvents)
        self.label_4.setObjectName(("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 2, 1, 1, 1)
        self.removeClusters = QtWidgets.QCheckBox(self.groupTimeEvents)
        self.removeClusters.setObjectName(("removeClusters"))
        self.gridLayout_8.addWidget(self.removeClusters, 1, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupTimeEvents, 1, 0, 1, 1)
        self.results = QtWidgets.QTableWidget(self.splitter_2)
        self.results.setMouseTracking(True)
        self.results.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.results.setAlternatingRowColors(True)
        self.results.setRowCount(0)
        self.results.setColumnCount(2)
        self.results.setObjectName(("results"))
        item = QtWidgets.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(False)
        item.setFont(font)
        self.results.setHorizontalHeaderItem(1, item)
        self.results.horizontalHeader().setStretchLastSection(True)
        self.results.verticalHeader().setStretchLastSection(False)
        self.groupVisualize = QtWidgets.QGroupBox(self.splitter_2)
        self.groupVisualize.setObjectName(("groupVisualize"))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupVisualize)
        self.horizontalLayout_5.setObjectName(("horizontalLayout_5"))
        self.label = QtWidgets.QLabel(self.groupVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.visRadius = QtWidgets.QSpinBox(self.groupVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visRadius.sizePolicy().hasHeightForWidth())
        self.visRadius.setSizePolicy(sizePolicy)
        self.visRadius.setMinimum(1)
        self.visRadius.setMaximum(100)
        self.visRadius.setProperty("value", 15)
        self.visRadius.setObjectName(("visRadius"))
        self.horizontalLayout_5.addWidget(self.visRadius)
        self.label_2 = QtWidgets.QLabel(self.groupVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.visAlpha = QtWidgets.QSpinBox(self.groupVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visAlpha.sizePolicy().hasHeightForWidth())
        self.visAlpha.setSizePolicy(sizePolicy)
        self.visAlpha.setMinimum(1)
        self.visAlpha.setMaximum(100)
        self.visAlpha.setProperty("value", 50)
        self.visAlpha.setObjectName(("visAlpha"))
        self.horizontalLayout_5.addWidget(self.visAlpha)
        self.label_5 = QtWidgets.QLabel(self.groupVisualize)
        self.label_5.setObjectName(("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.colorScale = QtWidgets.QDoubleSpinBox(self.groupVisualize)
        self.colorScale.setDecimals(1)
        self.colorScale.setMaximum(10.0)
        self.colorScale.setSingleStep(0.1)
        self.colorScale.setProperty("value", 1.0)
        self.colorScale.setObjectName(("colorScale"))
        self.horizontalLayout_5.addWidget(self.colorScale)
        self.visUseTime = QtWidgets.QCheckBox(self.groupVisualize)
        self.visUseTime.setObjectName(("visUseTime"))
        self.horizontalLayout_5.addWidget(self.visUseTime)
        self.visButton = QtWidgets.QPushButton(self.groupVisualize)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visButton.sizePolicy().hasHeightForWidth())
        self.visButton.setSizePolicy(sizePolicy)
        self.visButton.setObjectName(("visButton"))
        self.horizontalLayout_5.addWidget(self.visButton)
        self.exportImage = QtWidgets.QPushButton(self.groupVisualize)
        self.exportImage.setObjectName(("exportImage"))
        self.horizontalLayout_5.addWidget(self.exportImage)
        self.exportData = QtWidgets.QPushButton(self.groupVisualize)
        self.exportData.setObjectName(("exportData"))
        self.horizontalLayout_5.addWidget(self.exportData)
        self.exportVideo = QtWidgets.QPushButton(self.groupVisualize)
        self.exportVideo.setObjectName(("exportVideo"))
        self.horizontalLayout_5.addWidget(self.exportVideo)
        self.exportCancel = QtWidgets.QPushButton(self.groupVisualize)
        self.exportCancel.setObjectName(("exportCancel"))
        self.horizontalLayout_5.addWidget(self.exportCancel)
        self.gridLayout_7.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.searchWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(("progressBar"))
        self.gridLayout_7.addWidget(self.progressBar, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.splitterSearch)
        self.tabWidget.addTab(self.tabSearch, (""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.listArea.layout().setSpacing(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.playButton.setShortcut(_translate("MainWindow", "Space", None))
        self.propertyWidget.headerItem().setText(0, _translate("MainWindow", "Property", None))
        self.propertyWidget.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.buttonVariables.setText(_translate("MainWindow", "Variables", None))
        self.items.setSortingEnabled(True)
        item = self.items.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Path", None))
        self.filterTracks.setText(_translate("MainWindow", "Filter", None))
        self.checkAll.setText(_translate("MainWindow", "Check/Uncheck All", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEdit), _translate("MainWindow", "Edit", None))
        self.useAOIs.setText(_translate("MainWindow", "Use AOIs", None))
        self.updateStats.setText(_translate("MainWindow", "Update Stats", None))
        self.exportStats.setText(_translate("MainWindow", "Export Stats", None))
        self.exportAOIData.setText(_translate("MainWindow", "Export Individual Data", None))
        self.showHistogram.setText(_translate("MainWindow", "Show Data Histogram", None))
        item = self.aois.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "AOI", None))
        item = self.aois.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Average Duration (no zeros)", None))
        item = self.aois.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Percentage Fixated", None))
        item = self.aois.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Number of Subjects", None))
        self.searchButton.setText(_translate("MainWindow", "Search", None))
        self.searchCancel.setText(_translate("MainWindow", "Cancel", None))
        self.groupTimeEvents.setTitle(_translate("MainWindow", "Events", None))
        self.startTimeFilter.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.timeCheckBox.setText(_translate("MainWindow", "Time", None))
        self.stopTimeFilter.setDisplayFormat(_translate("MainWindow", "hh:mm:ss", None))
        self.maxClusterDistance.setSuffix(_translate("MainWindow", "%", None))
        self.maxClusterTime.setSuffix(_translate("MainWindow", " sec", None))
        self.label_3.setText(_translate("MainWindow", "Max Cluster Distance", None))
        self.label_4.setText(_translate("MainWindow", "Max Cluster Time", None))
        self.removeClusters.setText(_translate("MainWindow", "Remove Clustered Points", None))
        self.results.setSortingEnabled(True)
        item = self.results.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.results.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Time", None))
        self.groupVisualize.setTitle(_translate("MainWindow", "Visualization", None))
        self.label.setText(_translate("MainWindow", "Radius", None))
        self.visRadius.setSuffix(_translate("MainWindow", " %", None))
        self.label_2.setText(_translate("MainWindow", "Alpha", None))
        self.visAlpha.setSuffix(_translate("MainWindow", " %", None))
        self.label_5.setText(_translate("MainWindow", "Color Scale", None))
        self.visUseTime.setText(_translate("MainWindow", "Time", None))
        self.visButton.setText(_translate("MainWindow", "Visualize", None))
        self.exportImage.setText(_translate("MainWindow", "Export Image", None))
        self.exportData.setText(_translate("MainWindow", "Export Data", None))
        self.exportVideo.setText(_translate("MainWindow", "Export Video", None))
        self.exportCancel.setText(_translate("MainWindow", "Cancel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSearch), _translate("MainWindow", "Search", None))

from annotateview import AnnotateView
from aoitablewidget import AOITableWidget
from pathtablewidget import PathTableWidget
from propertywidget import PropertyWidget
